import React from 'react'
import {
  AlertTriangle,
  ArrowLeftRight,
  ArrowRight,
  Baby,
  Banknote,
  BarChart3,
  Bell,
  Briefcase,
  Building2,
  CalendarDays,
  Car,
  Check,
  ChevronDown,
  Clock,
  Coins,
  Compass,
  CreditCard,
  Download,
  Dumbbell,
  FileText,
  Film,
  Filter,
  Gem,
  Gift,
  GraduationCap,
  HelpCircle,
  Home,
  Hourglass,
  Info,
  Landmark,
  Laptop,
  LayoutDashboard,
  LifeBuoy,
  LineChart,
  Luggage,
  Menu,
  Minus,
  Package,
  Palmtree,
  PawPrint,
  Pencil,
  PieChart,
  PiggyBank,
  Pill,
  Plane,
  Plus,
  Receipt,
  Repeat,
  Ruler,
  Scale,
  Scissors,
  Search,
  Settings,
  Shirt,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Target,
  TrendingDown,
  TrendingUp,
  Trash2,
  Upload,
  UtensilsCrossed,
  Wallet,
  Wrench,
  X,
  Zap,
} from 'lucide-react'


export const ICONS = {
  home: Home,
  cart: ShoppingCart,
  car: Car,
  utilities: Zap,
  entertainment: Film,
  health: Pill,
  phone: Smartphone,
  package: Package,
  food: UtensilsCrossed,
  clothes: Shirt,
  travel: Plane,
  education: GraduationCap,
  pet: PawPrint,
  gift: Gift,
  fitness: Dumbbell,
  beauty: Scissors,
  bill: Receipt,
  work: Briefcase,
  tools: Wrench,
  extra: Sparkles,
  money: Banknote,
  invest: TrendingUp,
  emergency: LifeBuoy,
  beach: Palmtree,
  laptop: Laptop,
  ring: Gem,
  baby: Baby,
  luggage: Luggage,
  medical: Stethoscope,
  coins: Coins,
  bank: Landmark,
  cash: Wallet,
  savings: PiggyBank,
  credit: CreditCard,
  dashboard: LayoutDashboard,
  list: FileText,
  analyze: Search,
  forecast: LineChart,
  target: Target,
  budget: Ruler,
  recurring: Repeat,
  settings: Settings,
  plus: Plus,
  minus: Minus,
  edit: Pencil,
  trash: Trash2,
  close: X,
  menu: Menu,
  arrowRight: ArrowRight,
  transfer: ArrowLeftRight,
  check: Check,
  warning: AlertTriangle,
  info: Info,
  bell: Bell,
  up: TrendingUp,
  down: TrendingDown,
  scale: Scale,
  calendar: CalendarDays,
  clock: Clock,
  hourglass: Hourglass,
  compass: Compass,
  pie: PieChart,
  bars: BarChart3,
  filter: Filter,
  chevronDown: ChevronDown,
  download: Download,
  upload: Upload,
  building: Building2,
  unknown: HelpCircle,
} as const

export type IconKey = keyof typeof ICONS

export function isIconKey(v: unknown): v is IconKey {
  return typeof v === 'string' && v in ICONS
}

export function Icon({
  name,
  size = 16,
  className,
  style,
  strokeWidth = 1.75,
}: {
  name: IconKey | string | undefined
  size?: number
  className?: string
  style?: React.CSSProperties
  strokeWidth?: number
}) {
  const Cmp = (isIconKey(name) ? ICONS[name] : ICONS.unknown) as React.ComponentType<any>
  return (
    <Cmp size={size} className={className} style={style} strokeWidth={strokeWidth} aria-hidden />
  )
}

export const CATEGORY_ICON_KEYS: IconKey[] = [
  'home',
  'cart',
  'car',
  'utilities',
  'entertainment',
  'health',
  'phone',
  'package',
  'food',
  'clothes',
  'travel',
  'education',
  'pet',
  'gift',
  'fitness',
  'beauty',
  'bill',
  'work',
  'tools',
  'extra',
  'money',
  'invest',
]

export const GOAL_ICON_KEYS: IconKey[] = [
  'emergency',
  'beach',
  'car',
  'home',
  'laptop',
  'education',
  'ring',
  'baby',
  'gift',
  'luggage',
  'medical',
  'coins',
]

export const ACCOUNT_ICON: Record<string, IconKey> = {
  bank: 'bank',
  cash: 'cash',
  savings: 'savings',
  investment: 'invest',
  credit: 'credit',
}

export const EMOJI_TO_KEY: Record<string, IconKey> = {
  '🏠': 'home',
  '🛒': 'cart',
  '🚗': 'car',
  '💡': 'utilities',
  '🎬': 'entertainment',
  '💊': 'health',
  '📱': 'phone',
  '📦': 'package',
  '🍽️': 'food',
  '👕': 'clothes',
  '✈️': 'travel',
  '🎓': 'education',
  '🐾': 'pet',
  '🎁': 'gift',
  '🏋️': 'fitness',
  '💇': 'beauty',
  '🧾': 'bill',
  '💼': 'work',
  '🧰': 'tools',
  '✨': 'extra',
  '💰': 'money',
  '📈': 'invest',
  '🛟': 'emergency',
  '🏖️': 'beach',
  '💻': 'laptop',
  '💍': 'ring',
  '👶': 'baby',
  '🧳': 'luggage',
  '🩺': 'medical',
  '🪙': 'coins',
}

export function normalizeIcon(value: unknown, fallback: IconKey = 'package'): IconKey {
  if (isIconKey(value)) return value
  if (typeof value === 'string' && EMOJI_TO_KEY[value]) return EMOJI_TO_KEY[value]
  return fallback
}
